import os
import re
from openai import OpenAI


def _fallback_summary(title: str, text: str, topic: str, limit=650):
    """
    Generate a simple fallback summary for a news article.

    This function extracts the first 2–3 sentences from the provided text and trims the result
    to the specified character limit. If the resulting summary is empty, it returns the title,
    or a generic topic-based update if the title is also missing.

    Parameters
    ----------
    title : str
        The title of the article.
    text : str
        The main text content of the article.
    topic : str
        The topic of the article, used for a generic fallback if needed.
    limit : int, optional
        Maximum length of the summary in characters (default is 650).

    Returns
    -------
    str
        A concise summary of the article, or a fallback string if insufficient content.

    Notes
    -----
    - Sentences are detected using punctuation (., !, ?).
    - The summary is trimmed at the last whole word within the limit.
    - Used when the main summarization method is unavailable or fails.
    """
    # Take first 2–3 sentences, trim to limit
    sents = re.split(r'(?<=[.!?])\s+', text.strip())
    short = " ".join(sents[:3]).strip()
    if len(short) > limit:
        short = short[:limit].rsplit(" ", 1)[0] + "..."
    return short or (title if title else f"{topic.capitalize()} update")


def summarize(title: str, text: str, chosen_topic: str):
    """
    Generate a concise summary of a news article using OpenAI's GPT model, with fallback.

    This function attempts to summarize the provided article title and text into three
    concise sentences in English, focusing on the specified topic. If the OpenAI API key
    is not set or the API call fails, it falls back to a simple summary based on the first
    few sentences of the text.

    Parameters
    ----------
    title : str
        The title of the article.
    text : str
        The main text content of the article.
    chosen_topic : str
        The topic to emphasize in the summary.

    Returns
    -------
    str
        A concise summary of the article, either generated by the OpenAI API or a fallback summary.

    Notes
    -----
    - Uses the OPENAI_API_KEY environment variable for authentication.
    - Limits the article text to the first 3500 characters for the API prompt.
    - Falls back to the _fallback_summary function if the API key is missing or an error occurs.
    """
    # If caller passed an English normalization, use it
    title = title or ""
    text = text or ""
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        return _fallback_summary(title, text, chosen_topic)

    try:
        client = OpenAI(api_key=api_key)
        prompt = f"""
Summarize the following news article in 3 concise sentences (English).
Topic: {chosen_topic}
Title: {title}
Article:
{text[:3500]}
Only return the summary.
"""
        rsp = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.2,
        )
        out = rsp.choices[0].message.content.strip()
        if not out:
            return _fallback_summary(title, text, chosen_topic)
        return out
    except Exception:
        return _fallback_summary(title, text, chosen_topic)
